import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Text, UnorderedList, ListItem, Link, Box, Divider } from '@chakra-ui/react'
import Header from '@/components/header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <Header></Header>

        <Box px="32px">
          <Text fontSize='4xl' mb="4">Popular Packages</Text>

          <Divider mb="4" />

          <UnorderedList>
            <ListItem listStyleType="none" mb="1"><Link href="/package/express-generate">Lorem ipsum dolor sit amet</Link></ListItem>
            <ListItem listStyleType="none" mb="1"><Link href="/package/express-generate">Consectetur adipiscing elit</Link></ListItem>
            <ListItem listStyleType="none" mb="1"><Link href="/package/express-generate">Integer molestie lorem at massa</Link></ListItem>
            <ListItem listStyleType="none" mb="1"><Link href="/package/express-generate">Facilisis in pretium nisl aliquet</Link></ListItem>
          </UnorderedList>
        </Box>
      </main>
    </>
  )
}
